name: Print Project Info

on: workflow_dispatch

jobs:
  print_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Project Info
      run: |
        echo "Project Name: $GITHUB_REPOSITORY"
        echo "Current Branch: $GITHUB_REF"
