name: Build and Run Project

on: workflow_dispatch

jobs:
  run_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '6.0'
          
    - name: Install Android workload
      run: dotnet workload install maui-android

    - name: Build and run .NET MAUI project
      run: dotnet build -t:Run -p:Platform=Android -p:Configuration=Debug


